### ISSUE TITLE
Memory issue related to spring-boot-actuator + HdrHistogram

### ISSUE THREAD

**Issue by jordillachmrf** [rubicon-project/prebid-cache-java#1]
We are having a memory usage related issue with prebid-cache-java. 

We were able to reproduce the problem and got some snapshots that highlight a lot of memory pressure. 

To our understanding the culprit is the combo of spring-boot-actuator and hdrhistogram library (https://hdrhistogram.github.io/HdrHistogram/) which is a transitive dependency of the former

|INFO] +-org.springframework.boot:spring-boot-starter-actuator:jar:2.0.0.RC2:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.0.0.RC2:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-actuator:jar:2.0.0.RC2:compile
[INFO] |  |  \- org.springframework:spring-context:jar:5.0.4.RELEASE:compile
[INFO] |  |     \- org.springframework:spring-expression:jar:5.0.4.RELEASE:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.0.0:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.10:compile

Here are the snapshots, BTW we are using prebid-cache-java with the manage profile active

![memory_high](https://user-images.githubusercontent.com/33347279/39625986-59d546e2-4fa0-11e8-8dd6-7f437a3f6590.png)

The memory just keeps increasing

![memory_increase](https://user-images.githubusercontent.com/33347279/39625996-65d682c6-4fa0-11e8-9ba2-3e1cd8ecb53e.png)

**Comment by bretg** [comment]
test

**Comment by TerentievEvgany** [comment]
When you use manage profile it means that you enable actuator, please try to run prebid-cache without this profile.

**Comment by jordillachmrf** [comment]
Thanks for the response. Yeah, absolutely that is what we are going to try. 

In fact I think that we could have some kind of cardinality problem as suggested in some comments in https://github.com/spring-projects/spring-boot/issues/11338 . But as we do not really need actuator, we will stop using it as you suggested

But do you think it could be feasible to update some project dependencies ?

Spring Boot RC2 is still being used while 2.0.1 was released a while ago https://spring.io/blog/2018/04/05/spring-boot-2-0-1-available-now
In 2.0.1 there are, not related to this issue, lots of bugfixes and improvements done in actuator, micrometerio, spring-core, ...
Also please consider updating project-reactor which has been intesively bug fixed and improved lately https://github.com/reactor/reactor-core/releases

**Comment by TerentievEvgany** [comment]
Sure, I agree with You,  I'll update all dependencies soon.

**Comment by TerentievEvgany** [comment]
Hi Jordi, all dependencies was updated.
