### ISSUE TITLE
CPU thread stuck

### ISSUE THREAD

**Issue by jordillachmrf** [rubicon-project/prebid-cache-java#2]
Although not usual we've also suffered from a "stuck" thread, when the application has no problems with memory. 

In the following snapshots you can see how a single thread is using a lot of cpu, the thread just jumps from one snapshot to the other(I mean there's no other state, "live lock"?)

![cpu_problem_1](https://user-images.githubusercontent.com/33347279/39626185-33284750-4fa1-11e8-931c-aaad88915bfc.png)
![cpu_problem_2](https://user-images.githubusercontent.com/33347279/39626187-35f01f26-4fa1-11e8-8460-29083019978d.png)

**Comment by TerentievEvgany** [comment]
Our application is based on Spring Web Flux that used Rsactor project. Please read more about features of this project: http://projectreactor.io/docs/core/release/reference/#schedulers and http://projectreactor.io/docs/core/release/reference/#threading. Regarding schedulers we are using parallel.

**Comment by jordillachmrf** [comment]
Thanks for the feedback, some thoughts about this issue

As boot-2.0.0-RC2 depends on undertow-1.4.22.Final which depends on xnio-3.3.8, released in June 2017 (https://mvnrepository.com/artifact/org.jboss.xnio/xnio-nio/3.3.8.Final), some of the bug fixes done in xnio is "not available" to us, https://github.com/xnio/xnio/pull/126 (PR regarding https://issues.jboss.org/browse/XNIO-265, issue which by the way is not yet resolved)

In fact, I think that not even with the latest available boot-undertow module https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-undertow/2.0.1.RELEASE we can get rid of this xnio version.

I have no experience with Undertow but I have to say that I am little bit worried about issues like the afore mentioned https://issues.jboss.org/browse/XNIO-265, and also https://issues.jboss.org/browse/XNIO-244 

Most of the stack traces attached to those issues are pretty much the same of the ones I attached here, specially XNIO-265

**Comment by TerentievEvgany** [comment]
As we discussed, undertow will be replaced with netty.

**Comment by TerentievEvgany** [comment]
Hi Jordi, undertow was replaced with netty
