### ISSUE TITLE
Could not run the prebid-cache locally

### ISSUE THREAD

**Issue by rubypt1** [rubicon-project/prebid-cache-java#26]
I cloned the project and run in my local machine using aerospike. I followed the instructions given in README.md but I am getting the following issue,

`Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.prebid.cache.repository.ReactiveRepository<org.prebid.cache.model.PayloadWrapper, java.lang.String>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

Kindly help me resolving this issue to make the server up and running

**Comment by schernysh** [comment]
May I ask you to share the configuration you are using to run the application?

**Comment by TerentievEvgany** [comment]
Also need next information: what storage for prebid cache do you use aerospike or redis?

**Comment by rubypt1** [comment]
> Also need next information: what storage for prebid cache do you use aerospike or redis?

I am using aerospike

**Comment by rubypt1** [comment]
> May I ask you to share the configuration you are using to run the application?

I did not change any of the existing configurations. The following is the configuration from application.yml,

> info.app.name: @project.name@
info.app.artifact: @project.artifactId@
info.app.description: @project.description@
info.app.version: @project.version@
spring.main.banner-mode: "off"
api.path: /cache
server.port: 8080
server.compression.enabled: true
#server.compression.min-response-size: 1
#server.compression.mime-types: application/json,application/xml

# cors
cors:
  enabled: false
  mapping: "/cache/**"
  allowedOrigins: "*"
  allowedMethods: GET,POST
  allowCredentials: true

# cache
cache:
  prefix: prebid_
  expiry_sec: 300
  timeout_ms: 300

# logging
logging.level.root: info
logging.config: classpath:log4j2-console.xml

# metrics
metrics:
  graphite:
    enabled: false
    host: localhost
    port: 2003
    prefix: prebid

# circuit breaker
circuitbreaker:
  failure_rate_threshold: 50
  open_state_duration: 60000
  closed_state_calls_number: 5
  half_open_state_calls_number: 3

# endpoint actuators
management.health.defaults.enabled: false
management.endpoints.enabled-by-default: false
management.endpoints.web.base-path: /
management.health.diskspace.enabled: true
management.health.redis.enabled: false
management.endpoints.web.exposure.include: info, health, metrics, env, configprops
management.endpoint.info.enabled: true
management.endpoint.health.enabled: true
management.endpoint.metrics.enabled: true
management.endpoint.env.enabled: true
management.endpoint.configprops.enabled: true
management.endpoint.health.show-details: always
management.endpoint.shutdown.enabled: false
management.endpoint.configprops.keys-to-sanitize: password,secret,key,token,.*credentials.*,vcap_services
management.endpoint.info.cache.time-to-live: 5s
management.endpoint.health.cache.time-to-live: 5s
management.endpoint.metrics.cache.time-to-live: 5s
management.endpoint.env.cache.time-to-live: 5s
management.endpoint.configprops.cache.time-to-live: 5s

# undertow
server.undertow.buffer-size: 16384
server.undertow.direct-buffers: true

---
spring.profiles: manage
management.health.defaults.enabled: true
cors:
  enabled: true
metrics:
  graphite:
    enabled: true

---
spring.profiles: local
cache.expiry_sec: 300
cache:
  min_expiry: 15
  max_expiry: 28800
  allow_external_UUID: true
  secondary_cache_path: "cache"

metrics.graphite.enabled: false
spring:
  aerospike:
    port: 3000
    host: localhost
    cores: 4
    password:
    first_backoff: 300
    max_backoff: 1000
    max_retry: 3
    namespace: "prebid_cache"
    prevent_UUID_duplication: true

---
# dev
spring.profiles: dev
cache.expiry_sec: 28800
logging.level.root: debug
logging.config: classpath:log4j2-dev.xml

---
# qa
spring.profiles: qa
logging.level.root: info
logging.config: classpath:log4j2-qa.xml

---
# prod
spring.profiles: prod
management.endpoint.metrics.enabled: false
management.endpoint.env.enabled: false
management.endpoint.configprops.enabled: false
logging.level.root: warn
logging.config: classpath:log4j2-prod.xml

**Comment by TerentievEvgany** [comment]
One more question how do you run application?  Local profile for application should be specified. If you run prebid cache with terminal just add  -Dspring.profiles.active=local to the command, if you use IDE to run it  just edit run configuration.

**Comment by rubypt1** [comment]
I run the application locally. I tried with the suggestion provided but still, I am unable to start the cache server

`***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in org.prebid.cache.handlers.GetCacheHandler required a bean of type 'org.prebid.cache.repository.ReactiveRepository' that could not be found.


Action:

Consider defining a bean of type 'org.prebid.cache.repository.ReactiveRepository' in your configuration.
`

**Comment by TerentievEvgany** [comment]
Please, got to the prebid-cache-java/target and try to run next: java -jar -Dspring.profiles.active=local prebid-cache.jar

**Comment by rubypt1** [comment]
Using java -jar -Dspring.profiles.active=local prebid-cache.jar worked!! 

Thanks
